[package]
name = "pug"
version = "0.1.0"
authors = ["Ryan Joseph <ryan@proxy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.13.0"