[package]
name = "pug"
version = "0.0.1"
authors = ["Ryan Joseph <ryan.joseph@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.13.0"
regex = "1"